trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: BuildJob
    steps: 
    - bash: echo "Perform Build"

- stage: DevEnv
  jobs:
  - deployment: DevDeployment
    environment: Dev
    strategy:
     runOnce:
       deploy:
        steps:
           - script: echo Deploy at Dev Env

- stage: QAEnv
  jobs:
  - deployment: QADeployment
    environment: QA
    strategy:
     runOnce:
       deploy:
        steps:
           - script: echo Deploy at QA env          

- stage: STAGEEnv
  jobs:
  - deployment: StageDeployment
    environment: Stage
    strategy:
     runOnce:
       deploy:
        steps:
           - script: echo Deploy at Stage env
  
- stage: PRODEnv
  jobs:
  - deployment: PRODDeployment
    environment: PROD
    strategy:
     runOnce:
       deploy:
        steps:
           - script: echo Deploy at PROD env
        
